### ISSUE TITLE
Add YamlDotNet to the NuGet package

### ISSUE THREAD

**Issue by swiebertje** [PMudra/ApiCheck#15]
I noticed that I've forgot to add YamlDotNet to the NuGet package with the changes made in #13.

**Comment by swiebertje** [comment]
Added PR #16.

**Comment by PMudra** [comment]
The dependencies of the console project has to be corrected as well. I will do that myself because it was not your mistake in the first place.

**Comment by PMudra** [comment]
Nevermind. The console application is deployed as tool using nuget. Thus the root library must be in the tools dir, too. So I think its all good for now.

**Comment by swiebertje** [comment]
In my PR I've added the CommandLineParser dependency to the console package. Was that correct then? Anyway thanks for merging.

**Comment by PMudra** [comment]
I think the dependency has to be added to the package itself as dll. I will handle this and publish a new version.

**Comment by PMudra** [comment]
I published the new version.

**Comment by swiebertje** [comment]
Thanks for the updated package.
