### ISSUE TITLE
Does not work with .Net Core 3.1

### ISSUE THREAD

**Issue by ErwinBakels** [PMudra/ApiCheck#21]
Please upgrade to .Net Standard, so we can use it in .Net Core

**Comment by PMudra** [comment]
Thanks for the request @ErwinBakels. Please note that this repo has not been worked on for some time now. If you want this enhancement please feel free to fork and create a PR.

**Comment by ErwinBakels** [comment]
Thans, will do.

Question, is it allowed to have the source code in my solution? Or do I
always need the nuget package

Erwin

Op wo 27 mei 2020 14:56 schreef Philipp Mudra <notifications@github.com>:

**Comment by PMudra** [comment]
I am not quiet sure what your question is. This project is licensed under MIT so you can pretty much do anything with this source code (e.g. include and modify in your own repos or solutions).
Please see https://choosealicense.com/licenses/mit/

Anyhow, it would be nice if you contribute any enhancements back into this repo (or even in your own NuGet package).

**Comment by Nico-1987** [comment]
> I am not quiet sure what your question is. This project is licensed under MIT so you can pretty much do anything with this source code (e.g. include and modify in your own repos or solutions). Please see https://choosealicense.com/licenses/mit/
> 
> Anyhow, it would be nice if you contribute any enhancements back into this repo (or even in your own NuGet package).

@PMudra 
We would like to add support for future .NET platforms by upgrading the projects targetFramework to NetStandard2.0.
Before we do we would like to ask you, are you oke migrating the entire library to NetStandard2.0 only, or do you expect the new version to still work on < .NET 4.6.1.

**Comment by ErwinBakels** [comment]
Wow, that was a long time ago. In my current job i don't use it anymore.

But the original question was, that they wanted to recompile the sourcecode so it could be used in NetCore 3.1. (or .NetStandard 2.0).

They were migrating from Net4.7.2 to NetCore 3.1.
