### ISSUE TITLE
Comparer crashed while comparing default parameter System.DateTime

### ISSUE THREAD

**Issue by ppslde** [PMudra/ApiCheck#24]
Hi Philipp,

we encountered a problem while checking method signatures:

In our code base, we have often notations like this:
```csharp
public void M(DateTime d = default(DateTime)){
   //...
}
```
When the ApiCheck is comparing this signature and especially the parameter of type ```System.DateTime```, the used reflection method 'RawDefaultValue' throws an exception: 

> Encountered an invalid type for a default value.
>    at System.Reflection.MdConstant.GetValue(MetadataImport scope, Int32 token, RuntimeTypeHandle fieldTypeHandle, Boolean raw)
>    at System.Reflection.RuntimeParameterInfo.GetDefaultValueInternal(Boolean raw)
>    at System.Reflection.RuntimeParameterInfo.GetDefaultValue(Boolean raw)
>    at ApiCheck.Comparer.ParameterComparer.CompareDefaultValue() in C:\Sources.Danny\ApiCheck\ApiCheck\Comparer\ParameterComparer.cs:line 28

My proposal would be, to add different behavior for type ```System.DateTime``` and maybe others (where default value behavior is currently not implemented by framework, refer [https://github.com/dotnet/runtime/issues/18844](https://github.com/dotnet/runtime/issues/18844)).

What would be your proposal for this problem?
Can you and will you going to fix it?

Thank you and
Kind regards
Danny

**Comment by PMudra** [comment]
Hi @ppslde,

thanks for reaching out. As you might have noticed, this repo is not in active development. I am not going to work on any fixes myself. But I'd gladly review and accept any pull requests that you provide.

That being said, this feels like a bug in the framework which is unfortunate. I agree that a workaround should be added when the parameter type is `DateTime` (and others like `Guid`).
