### ISSUE TITLE
Add support for modern .NET platforms

### ISSUE THREAD

**Issue by Nico-1987** [PMudra/ApiCheck#26]
We would like to add support for future .NET platforms by upgrading the ApiCheck projects targetFramework to NetStandard2.0.

Before we do we would like to ask you, are you oke migrating the entire library to NetStandard2.0 only, or do you expect the new version to still work on < .NET 4.6.1.
If we can move away from < .NET 4.6.1 we can modernize the project structure.

After your confirmation, we are planning to submit a pull request with changes

**Comment by PMudra** [comment]
Hello @Nico-1987, thanks for reaching out. As far as I can tell, porting to .NET Standard is a good idea. So please go ahead.

We will just have to bump the major version of the nuget package as this will be a breaking change.

To be honest, I don't have much knowledge about .NET Standard and I am not able to support you much. Please don't hesitate to fork this repo and publish your own package if that works better for you.

**Comment by Nico-1987** [comment]
Thank you @PMudra, we will make a fork in the near future and make these changes.

**Comment by swiebertje** [comment]
This is now implemented with #27
